# Generated by Django 3.0.8 on 2020-08-03 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_itemdetails'),
    ]


