# Generated by Django 3.0.8 on 2020-08-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200805_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='stat',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SelectItem', to='auctions.itemDetails'),
        ),
    ]
